[tool.poetry]
name = "open-optical-gating"
version = "1.0.0"
description = ""
authors = ["Chas Nelson <chas.nelson@glasgow.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.7"
optical-gating-alignment = { git = "https://github.com/Glasgow-ICG/optical-gating-alignment" }
loguru = "^0.4.1"
tqdm = "^4.45.0"
pandas = "^1.0.3"
scikit-image = "^0.16.2"
serial = "^0.0.97"
flask = "^1.1.2"
# RPi Specific
picamera = { version = "^1.13", optional = true}
fastpins = { git = "https://github.com/abdrysdale/fastpins" , optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pytest-cov = "^2.8.1"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
